### ISSUE TITLE
REST Methoden

### ISSUE THREAD

**Issue by jowieweb** [nkohlmeier/Spezielle-Gebiete-zum-Softwareengineering#1]
Wir müssen uns mal überlegen wie wir im Grundsatz unsere Rest Methoden haben wollen.
Habe bis jetzt alle mit GET gebaut, um sie möglichst einfach testen zu können.

Create User: POST oder PUT?
Update Automation (name ändern oder deaktivieren): POST oder PUT?
Automation löschen: DELETE?

Die eigentliche Entscheidung:
Zum anlegen PUT, zum ändern POST?
Oder genau andersrum:
Zum anlegen POST, zum ändern PUST

In der KSE hieß es immer PUT zum ändern, aber das fand ich da schon kontraintuitiv :D

**Comment by nkohlmeier** [comment]
Moin.
Wir können auch zum Anlegen UND Ändern POST verwenden ;)
Mir ist es egal. Ich wäre auch mit GET zufrieden. Hauptsache, es läuft ;)

**Comment by jowieweb** [comment]
sehr schön. gefällt mir.
