### ISSUE TITLE
Automatisierungstabelle

### ISSUE THREAD

**Issue by jowieweb** [nkohlmeier/Spezielle-Gebiete-zum-Softwareengineering#5]
wollen wir das nicht anders darstellen? Ich hätte gerne mehrere Bedingungen und Aktionen richtig dargestellt.

Also ich würde "einfach" ne Combobox mit allen Automatisierungen machen. Da kann man dann eine auswählen. Dann werden 2 tabellen gefüllt: eine mit mit den "conditions" und eine mit den "actions" dann kann man da noch iwie "WENN :" tabelle "DANN " tabelle davor/zwischen schreiben... 

Dann noch n paar knöpfe verteilen (automation add und remove, Condition add und remove und action add und remove)

**Comment by nkohlmeier** [comment]
Im moment sieht es so aus:
![bildschirmfoto vom 2017-06-14 18-53-39](https://user-images.githubusercontent.com/27957732/27144623-e021fc94-5132-11e7-99c6-85180de3126b.png)

**Comment by nkohlmeier** [comment]
Ich bin am überlegen, ob wir AngularJS nehmen sollten. Mit Angular sind dynamische Tabelle einfacher zu implementieren...

**Comment by jowieweb** [comment]
aaaach, ich bau das mal "schnell" ;)

**Comment by nkohlmeier** [comment]
Ich habe den aktuellen Stand mal gepusht.

**Comment by jowieweb** [comment]
![grafik](https://user-images.githubusercontent.com/11941178/27148611-331578fa-5141-11e7-841b-1f43577af68d.png)

so dachte ich irgendwie...

**Comment by nkohlmeier** [comment]
Ok. Damit kann man auch Regeln mit mehreren Bedingungen erstellen. Das ist gut.

**Comment by jowieweb** [comment]
ich kanns ja mal in den backend branch pushen

**Comment by jowieweb** [comment]
https://github.com/nkohlmeier/Spezielle-Gebiete-zum-Softwareengineering/blob/backend/.SHP/SHP-Web/WebContent/index.html

da ist es.. 

achso, ich hab in /automation bei condition und action mal "device name" in "devicename" geändert. das nervte mich ;)

**Comment by nkohlmeier** [comment]
Ok. Kannst Du im Backend noch einbauen, dass man für das Anlegen von Regeln auch ein Automation-Objekt mit allen Conditions und Actions schicken kann?
Also. das man ein neues Objekt hinschickt und dann die neue ID zurückbekommt?

**Comment by jowieweb** [comment]
jop, gute idee...
